version: '3.9'

services:
  graphhopper:
    image: mouhamedtec/graphhopper:latest
    container_name: graphhopper
    restart: unless-stopped
    ports:
      - "8989:8989"
    volumes:
      - ./graphhopper-data:/data
    environment:
      - JAVA_OPTS=-Xmx2g
    labels:
      - traefik.enable=true
      - traefik.http.routers.graphhopper.rule=Host(`graphhopper.hayataxi.online`)
      - traefik.http.routers.graphhopper.entrypoints=websecure
      - traefik.http.routers.graphhopper.tls=true

  nominatim:
    image: mediagis/nominatim:4.1
    container_name: nominatim
    restart: unless-stopped
    volumes:
      - ./nominatim-data:/data
    environment:
      - POSTGRES_PASSWORD=nominatim
      - PBF=/data/yemen-latest.osm.pbf
    labels:
      - traefik.enable=true
      - traefik.http.routers.nominatim.rule=Host(`nominatim.hayataxi.online`)
      - traefik.http.routers.nominatim.entrypoints=websecure
      - traefik.http.routers.nominatim.tls=true

  tileserver:
    image: overv/openstreetmap-tile-server
    container_name: tileserver
    restart: unless-stopped
    ports:
   
       labels:
      - traefik.enable=true
      - traefik.http.routers.tiles.rule=Host(`tiles.hayataxi.online`)
      - traefik.http.routers.tiles.entrypoints=websecure
      - traefik.http.routers.tiles.tls=true
